# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1db750ed11bfc6256e5b206c30ee44b99a259b4ff4c0083cacca89df1c4acadff9b67520b2370bc6203a5ca4805a670db7a02706e9a311333f73e69f99734672

test:
  secret_key_base: 3977f415a55747ca1efeb2bd8c9326a809a8d2652c8e6f9d690863fedf026c946d77dc26fa4f07f49c8a9c712931c5536b7105e06cd830a96a9122bd2f0a5c05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
